/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaMedStore;

import java.awt.Component;
import java.time.LocalDate;
import java.util.Random;
import java.util.ArrayList;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;

/**
 *
 * @author sosin/Francis
 */
public class MedGui extends javax.swing.JFrame {

    /**
     * Creates new form MedGui
     */
    public MedGui() {
        initComponents();
        for (Component c : jPanel3.getComponents()) {
            c.setEnabled(false);
        }
        for (Component d : jPanel4.getComponents()) {
            d.setEnabled(false);
        }
        for (Component e : jPanel5.getComponents()) {
            e.setEnabled(false);
        }
        for (Component c : jPanel8.getComponents()) {
            c.setEnabled(false);
        }
        for (Component c : jPanel9.getComponents()) {
            c.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        passWd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        rentalReminder = new javax.swing.JTextArea();
        loginExtBtn = new javax.swing.JButton();
        infoGuide = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        userSign = new javax.swing.JTextField();
        passSign = new javax.swing.JTextField();
        signUpBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        passSign1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        signUpInform = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        purchaseName = new javax.swing.JTextField();
        buyBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseInform = new javax.swing.JTextArea();
        purchaseExtBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        productsPane = new javax.swing.JTextArea();
        getProducts = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rentName = new javax.swing.JTextField();
        rentBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rentInform = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        rentalExtBtn = new javax.swing.JButton();
        returnRqst = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        updateAdmin = new javax.swing.JButton();
        nameFld = new javax.swing.JTextField();
        qtyFld = new javax.swing.JTextField();
        costFld = new javax.swing.JTextField();
        insertAdmin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        retrnBtn1 = new javax.swing.JButton();
        itemName = new javax.swing.JTextField();
        renteeName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        rentUpdate = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        rentalinfo = new javax.swing.JTextArea();
        rentalgetBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        stockCntrlPan = new javax.swing.JTextArea();
        stockControl = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        userCntrlField = new javax.swing.JTextArea();
        userControl = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });

        passWd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passWdActionPerformed(evt);
            }
        });

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        rentalReminder.setColumns(20);
        rentalReminder.setRows(5);
        jScrollPane3.setViewportView(rentalReminder);

        loginExtBtn.setText("Exit");
        loginExtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginExtBtnActionPerformed(evt);
            }
        });

        infoGuide.setText("Help");
        infoGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoGuideActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel9.setText("Medical Items Inventory");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(infoGuide)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(passWd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(38, 38, 38)
                                    .addComponent(loginBtn)
                                    .addGap(161, 161, 161))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(89, 89, 89)
                                .addComponent(loginExtBtn)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(infoGuide)
                    .addComponent(loginExtBtn))
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passWd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Login", jPanel1);

        signUpBtn.setText("Sign Up");
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("Username :");

        jLabel13.setText("Password :");

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel14.setText("Sign Up Page");

        jLabel15.setText("Re-Enter Password:");

        signUpInform.setEditable(false);
        signUpInform.setColumns(20);
        signUpInform.setRows(5);
        jScrollPane8.setViewportView(signUpInform);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(userSign, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passSign)
                                .addComponent(passSign1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signUpBtn)
                            .addComponent(jLabel14))
                        .addGap(0, 254, Short.MAX_VALUE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(4, 4, 4)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(2, 2, 2)
                .addComponent(passSign1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sign Up", jPanel7);

        purchaseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseNameActionPerformed(evt);
            }
        });

        buyBtn.setText("Buy");
        buyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Product Name:");

        purchaseInform.setEditable(false);
        purchaseInform.setColumns(20);
        purchaseInform.setRows(5);
        jScrollPane1.setViewportView(purchaseInform);

        purchaseExtBtn.setText("Exit");
        purchaseExtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseExtBtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel16.setText("Purchase Equipment Page");

        productsPane.setEditable(false);
        productsPane.setColumns(20);
        productsPane.setRows(5);
        jScrollPane9.setViewportView(productsPane);

        getProducts.setText("Get Products");
        getProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addGap(37, 37, 37)
                                .addComponent(purchaseExtBtn)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(purchaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addComponent(buyBtn))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(getProducts)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(purchaseExtBtn))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(purchaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buyBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getProducts))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Purchase", jPanel3);

        rentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentNameActionPerformed(evt);
            }
        });

        rentBtn.setText("Rent");
        rentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Product Name:");

        rentInform.setEditable(false);
        rentInform.setColumns(20);
        rentInform.setRows(5);
        jScrollPane2.setViewportView(rentInform);

        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("NOTE: The Rental Period lasts 1 month");

        rentalExtBtn.setText("Exit");
        rentalExtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalExtBtnActionPerformed(evt);
            }
        });

        returnRqst.setText("Return");
        returnRqst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnRqstActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel17.setText("Rental Page");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(returnRqst))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rentalExtBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rentName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rentBtn)))
                        .addContainerGap(208, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rentalExtBtn)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentBtn))
                .addGap(12, 12, 12)
                .addComponent(returnRqst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rent", jPanel4);

        updateAdmin.setText("Update Existing");
        updateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAdminActionPerformed(evt);
            }
        });

        nameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFldActionPerformed(evt);
            }
        });

        costFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costFldActionPerformed(evt);
            }
        });

        insertAdmin.setText("Insert New");
        insertAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertAdminActionPerformed(evt);
            }
        });

        jLabel5.setText("Name");

        jLabel6.setText("Quantity");

        jLabel7.setText("Cost");

        retrnBtn1.setText("Remove Rental");
        retrnBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrnBtn1ActionPerformed(evt);
            }
        });

        itemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameActionPerformed(evt);
            }
        });

        renteeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renteeNameActionPerformed(evt);
            }
        });

        jLabel10.setText("Rentee:");

        jLabel11.setText("Product Name:");

        rentUpdate.setEditable(false);
        rentUpdate.setColumns(20);
        rentUpdate.setRows(5);
        jScrollPane4.setViewportView(rentUpdate);

        rentalinfo.setEditable(false);
        rentalinfo.setColumns(20);
        rentalinfo.setRows(5);
        jScrollPane5.setViewportView(rentalinfo);

        rentalgetBtn.setText("Get Rentals");
        rentalgetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalgetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(qtyFld, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(costFld, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateAdmin)
                                    .addComponent(jLabel11)
                                    .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(insertAdmin)
                                    .addComponent(jLabel10)
                                    .addComponent(renteeName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(retrnBtn1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rentalgetBtn))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateAdmin)
                            .addComponent(insertAdmin))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(renteeName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(retrnBtn1)
                    .addComponent(rentalgetBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanel5);

        stockCntrlPan.setEditable(false);
        stockCntrlPan.setColumns(20);
        stockCntrlPan.setRows(5);
        jScrollPane7.setViewportView(stockCntrlPan);

        stockControl.setText("Get Stock");
        stockControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockControlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(stockControl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stockControl)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Admin Stock", jPanel8);

        userCntrlField.setEditable(false);
        userCntrlField.setColumns(20);
        userCntrlField.setRows(5);
        jScrollPane6.setViewportView(userCntrlField);

        userControl.setText("Get Users");
        userControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userControlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userControl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(userControl))
        );

        jTabbedPane1.addTab("Admin User", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
ArrayList<String> inventoryArr = new ArrayList<String>();
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        //creating array list to hold user details and get text stored in input box for username
        ArrayList<String> deets = new ArrayList<String>();
        String userUsername = userName.getText();
        //creating array to hold existing rentals data 
        ArrayList<String> rentals = new ArrayList<String>();
        rentals = JavaMedProject.getRentals();
        //get text stored in input box for password and check if they exist in the db table
        String userPasswd = passWd.getText();
        deets = JavaMedProject.login(userUsername, userPasswd);
        //if user does not exist or if username or password is wrong state error and disable tabs
        if (deets.size() == 0 && deets.size() <= 3) {
            rentalReminder.setText("Incorrect username or password please try again");
            //disable all tabs
            for (Component c : jPanel3.getComponents()) {
                c.setEnabled(false);
            }
            for (Component d : jPanel4.getComponents()) {
                d.setEnabled(false);
            }
            for (Component e : jPanel5.getComponents()) {
                e.setEnabled(false);
            }
            //if user credentials are correct execute main code
        } else {
            //System.out.println(userUsername);
            //additional check if username and password match existing
            if (deets.get(0).equals(userUsername) && deets.get(1).equals(userPasswd)) {
                //check if user is the admin
                if (Integer.parseInt(deets.get(2)) == 1) {
                    //enable all tabs
                    for (Component c : jPanel3.getComponents()) {
                        c.setEnabled(true);
                    }
                    for (Component d : jPanel4.getComponents()) {
                        d.setEnabled(true);
                    }
                    for (Component e : jPanel5.getComponents()) {
                        e.setEnabled(true);
                    }
                    for (Component c : jPanel8.getComponents()) {
                        c.setEnabled(true);
                    }
                    for (Component c : jPanel9.getComponents()) {
                        c.setEnabled(true);
                    }
                    inventoryArr = JavaMedProject.getInventory();
                    System.out.println(inventoryArr);
                    //if user is not the admin
                } else {
                    //disable admin tab
                    for (Component e : jPanel5.getComponents()) {
                        e.setEnabled(false);
                    }
                    //if user has outstanding rentals disable rental tab and state user has outstanding rental
                    if (rentals.contains(userUsername)) {
                        rentalReminder.setText("Your account still shows item needs to be returned, you cannot rent until the item is returned.");
                        for (Component c : jPanel3.getComponents()) {
                            c.setEnabled(true);
                        }
                        inventoryArr = JavaMedProject.getInventory();
                        System.out.println(inventoryArr);
                        //if user has no outstanding rentals he/she may purchase or rent
                    } else {
                        for (Component c : jPanel3.getComponents()) {
                            c.setEnabled(true);
                        }
                        for (Component d : jPanel4.getComponents()) {
                            d.setEnabled(true);
                        }
                        inventoryArr = JavaMedProject.getInventory();
                        System.out.println(inventoryArr);
                        rentalReminder.setText("You have no outstanding rentals.");
                    }
                }
            }
        }
        //System.out.println(deets);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void passWdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passWdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passWdActionPerformed

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void purchaseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseNameActionPerformed

    private void buyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBtnActionPerformed
        // TODO add your handling code here:
        //get data stored in input box 'purchaseName'
        String purchase = purchaseName.getText();
        //check if database table has item user is looking to buy
        if (inventoryArr.contains(purchase)) {
            //get index of where in the inventory the item user is looking for
            int indexOfInv = inventoryArr.indexOf(purchase);
            System.out.println(indexOfInv);

            int indexOfId = indexOfInv - 1;
            int indexOfQty = indexOfInv + 1;
            int indexOfCost = indexOfInv + 2;
            long millis = System.currentTimeMillis();
            java.sql.Date date = new java.sql.Date(millis);
            String nameOfItm = inventoryArr.get(indexOfInv);
            System.out.println(inventoryArr.get(indexOfQty));
            int costOfItm = Integer.parseInt(inventoryArr.get(indexOfCost));
            JavaMedProject.insertPurchase(nameOfItm, date, costOfItm);
            int newQty = Integer.parseInt(inventoryArr.get(indexOfQty)) - 1;
            JavaMedProject.updateInv(newQty, Integer.parseInt(inventoryArr.get(indexOfId)));
            purchaseInform.setText("Purchase Successful your account has been charged");
        }

    }//GEN-LAST:event_buyBtnActionPerformed

    private void costFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costFldActionPerformed

    private void updateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAdminActionPerformed
        // TODO add your handling code here:
        String nameStr = nameFld.getText();
        int qtyInt = Integer.parseInt(qtyFld.getText());
        int costInt = Integer.parseInt(costFld.getText());
        int iDInt = Integer.parseInt(inventoryArr.get(inventoryArr.indexOf(nameStr) - 1));
        JavaMedProject.adminUpdateInv(nameStr, qtyInt, costInt, iDInt);
    }//GEN-LAST:event_updateAdminActionPerformed

    private void insertAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertAdminActionPerformed
        // TODO add your handling code here:
        String nameStr = nameFld.getText();
        int qtyInt = Integer.parseInt(qtyFld.getText());
        int costInt = Integer.parseInt(costFld.getText());
        JavaMedProject.adminInsertInventory(nameStr, qtyInt, costInt);
    }//GEN-LAST:event_insertAdminActionPerformed

    private void rentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentBtnActionPerformed
        // TODO add your handling code here:
        String nameStr = rentName.getText();
        int costOfProd = Integer.parseInt(inventoryArr.get(inventoryArr.indexOf(nameStr) + 2));
        // String costOfProd = inventoryArr.get(inventoryArr.indexOf(nameStr)+2);
        String rentee = userName.getText();
        System.out.println(nameStr);
        System.out.println(costOfProd);
        System.out.println(rentee);

        long millis = System.currentTimeMillis();
        java.sql.Date date = new java.sql.Date(millis);
        LocalDate ld = date.toLocalDate();
        LocalDate monthAdded = ld.plusMonths(1);
        java.sql.Date sqldate = java.sql.Date.valueOf(monthAdded);

        JavaMedProject.insertRental(nameStr, date, sqldate, costOfProd, rentee);
        rentInform.setText("The rental has been set, you can only have 1 rental at a time. There will be a penalty for not returning the item at: " + sqldate);
    }//GEN-LAST:event_rentBtnActionPerformed

    private void rentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentNameActionPerformed

    private void nameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFldActionPerformed

    private void itemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameActionPerformed

    private void renteeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renteeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_renteeNameActionPerformed

    private void retrnBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrnBtn1ActionPerformed
        // TODO add your handling code here:
        //get data stored in both fields
        String rentee = renteeName.getText();
        String itemName = rentName.getText();
        //find rental data based on two fields entered with the sql statement and remove item
        JavaMedProject.remvRental(itemName, rentee);

        rentUpdate.setText("Item returned, information updated successfully");
    }//GEN-LAST:event_retrnBtn1ActionPerformed

    private void rentalExtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalExtBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rentalExtBtnActionPerformed

    private void purchaseExtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseExtBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_purchaseExtBtnActionPerformed

    private void loginExtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginExtBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_loginExtBtnActionPerformed

    private void returnRqstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnRqstActionPerformed
        // TODO add your handling code here:
        ItemReturnForm itr = new ItemReturnForm();
        itr.show();
        dispose();

    }//GEN-LAST:event_returnRqstActionPerformed

    private void infoGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoGuideActionPerformed
        // TODO add your handling code here:
        System.out.println("\n!======================================================================================================!");
        System.out.println("Hello, this application will allow you to rent and buy listed hospital equipment.");
        System.out.println("You can buy or rent from the appropriate labelled tabs.");
        System.out.println("Only the administrator may remove rented equipment and insert data.");
        System.out.println("A return button on the rentals page allows you to inform that equipment has been returned.");
        System.out.println("You may only rent an item for a month, you must renew the rented item otherwise.");
        System.out.println("The exit button will close the program entirely and any uncompleted rents or buys wont be processed");
        System.out.println("Only existing username and password may use the hospital equipment database.");
        System.out.println("!======================================================================================================!");
        rentalReminder.setText("\n!======================================================================================================!\n"
                + "Hello, this application will allow you to rent and buy listed hospital equipment.\n"
                + "You can buy or rent from the appropriate labelled tabs.\n"
                + "Only the administrator may remove rented equipment and insert data.\n"
                + "A return button on the rentals page allows you to inform that equipment has been returned.\n"
                + "You may only rent an item for a month, you must renew the rented item otherwise.\n"
                + "The exit button will close the program entirely and any uncompleted rents or buys wont be processed\n"
                + "Only existing username and password may use the hospital equipment database.\n"
                + "!======================================================================================================!");

    }//GEN-LAST:event_infoGuideActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        // TODO add your handling code here:
        String name = userSign.getText();
        String passw = passSign.getText();
        String confpassw = passSign1.getText();
        if(confpassw.equals(passw)){
            JavaMedProject.insertUser(name, passw);
            signUpInform.setText("User has been created!");
        }else{
            signUpInform.setText("Passwords entered do not match please make sure passwords match in both fields.");
        }
        
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void rentalgetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalgetBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<String> rentals = new ArrayList<String>();
        rentals = JavaMedProject.getRentals();
        System.out.println(rentals);
        for (int i = 0; i < rentals.size(); i++) {
            rentalinfo.append(rentals.get(i) + "\n");
            System.out.println(rentals.get(i));
        }
    }//GEN-LAST:event_rentalgetBtnActionPerformed

    private void userControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userControlActionPerformed
        // TODO add your handling code here:
        ArrayList<String> userArr = new ArrayList<String>();
        userArr = JavaMedProject.getUsers();
        for (int i = 0; i < userArr.size(); i++) {
            userCntrlField.append(userArr.get(i) + "\n");
            System.out.println(userArr.get(i));
        }
    }//GEN-LAST:event_userControlActionPerformed

    private void stockControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockControlActionPerformed
        // TODO add your handling code here:
        ArrayList<String> inventory = new ArrayList<String>();
        inventory = JavaMedProject.getInventory();
        for (int i = 0; i < inventory.size(); i++) {
            stockCntrlPan.append(inventory.get(i) + "\n");
            System.out.println(inventory.get(i));
        }
    }//GEN-LAST:event_stockControlActionPerformed

    private void getProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getProductsActionPerformed
        // TODO add your handling code here:
        ArrayList<String> userInv = new ArrayList<String>();
        userInv = JavaMedProject.getUsrInventory();
        for (int i = 0; i < userInv.size(); i++) {
            productsPane.append(i+"\n");
            productsPane.append(userInv.get(i) + "\n");
            System.out.println(userInv.get(i));
        }
    }//GEN-LAST:event_getProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyBtn;
    private javax.swing.JTextField costFld;
    private javax.swing.JButton getProducts;
    private javax.swing.JButton infoGuide;
    private javax.swing.JButton insertAdmin;
    private javax.swing.JTextField itemName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton loginExtBtn;
    private javax.swing.JTextField nameFld;
    private javax.swing.JTextField passSign;
    private javax.swing.JTextField passSign1;
    private javax.swing.JTextField passWd;
    private javax.swing.JTextArea productsPane;
    private javax.swing.JButton purchaseExtBtn;
    private javax.swing.JTextArea purchaseInform;
    private javax.swing.JTextField purchaseName;
    private javax.swing.JTextField qtyFld;
    private javax.swing.JButton rentBtn;
    private javax.swing.JTextArea rentInform;
    private javax.swing.JTextField rentName;
    private javax.swing.JTextArea rentUpdate;
    private javax.swing.JButton rentalExtBtn;
    private javax.swing.JTextArea rentalReminder;
    private javax.swing.JButton rentalgetBtn;
    private javax.swing.JTextArea rentalinfo;
    private javax.swing.JTextField renteeName;
    private javax.swing.JButton retrnBtn1;
    private javax.swing.JButton returnRqst;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JTextArea signUpInform;
    private javax.swing.JTextArea stockCntrlPan;
    private javax.swing.JButton stockControl;
    private javax.swing.JButton updateAdmin;
    private javax.swing.JTextArea userCntrlField;
    private javax.swing.JButton userControl;
    private javax.swing.JTextField userName;
    private javax.swing.JTextField userSign;
    // End of variables declaration//GEN-END:variables
}
